/* Generated By:JJTree: Do not edit this line. ASTExpr.java */

package edu.washington.sig.gleen.javacc.grammar;

public @SuppressWarnings("all") class ASTExpr extends SimpleNode {
  public ASTExpr(int id) {
    super(id);
  }

  public ASTExpr(PathExpression p, int id) {
    super(p, id);
  }

}
