/* Generated By:JJTree: Do not edit this line. ASTSubExpr.java */

package edu.washington.sig.gleen.javacc.grammar;

public @SuppressWarnings("all") class ASTSubExpr extends SimpleNode {
  public ASTSubExpr(int id) {
    super(id);
  }

  public ASTSubExpr(PathExpression p, int id) {
    super(p, id);
  }

}
