/* Generated By:JJTree: Do not edit this line. ASTStart.java */

package edu.washington.sig.gleen.javacc.grammar;

public @SuppressWarnings("all") class ASTStart extends SimpleNode {
  public ASTStart(int id) {
    super(id);
  }

  public ASTStart(PathExpression p, int id) {
    super(p, id);
  }

}
