/* Generated By:JJTree: Do not edit this line. ASTSimpTerm.java */

package edu.washington.sig.gleen.javacc.grammar;

public @SuppressWarnings("all")
class ASTSimpTerm extends SimpleNode
{
	//private String property = "";
	
	public ASTSimpTerm(int id)
	{
		super(id);
	}

	public ASTSimpTerm(PathExpression p, int id)
	{
		super(p, id);
	}

	public void setOperator(String property)
	{
		// first strip off delimiters
		String propertyURI = property.substring(1, property.length()-1);
		super.setOperator(propertyURI);
	}
	
	public String toString()
	{
		return "property: "+this.getOperator();
	}
}
