/* Generated By:JavaCC: Do not edit this line. PathExpressionTreeConstants.java Version 4.1d1 */
package edu.washington.sig.gleen.javacc.grammar;

public interface PathExpressionTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTBINARYOPEXPR = 2;
  public int JJTUNARYOPEXPR = 3;
  public int JJTSIMPTERM = 4;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "BinaryOpExpr",
    "UnaryOpExpr",
    "SimpTerm",
  };
}
/* JavaCC - OriginalChecksum=6e36c4e9d9eefff2b395e15c885d9f19 (do not edit this line) */
