/* Generated By:JJTree&JavaCC: Do not edit this line. PathExpressionConstants.java */
package edu.washington.sig.gleen.javacc.grammar;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PathExpressionConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LGROUP = 7;
  /** RegularExpression Id. */
  int RGROUP = 8;
  /** RegularExpression Id. */
  int CONCAT = 9;
  /** RegularExpression Id. */
  int ALT = 10;
  /** RegularExpression Id. */
  int STAR = 11;
  /** RegularExpression Id. */
  int PLUS = 12;
  /** RegularExpression Id. */
  int OPT = 13;
  /** RegularExpression Id. */
  int PROPERTY = 14;
  /** RegularExpression Id. */
  int PROPERTY_CHAR = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"(\"",
    "\")\"",
    "\"/\"",
    "\"|\"",
    "\"*\"",
    "\"+\"",
    "\"?\"",
    "<PROPERTY>",
    "<PROPERTY_CHAR>",
  };

}
